import PDFDocument from "pdfkit";
import { formatReadingAge } from "../utils/readingAge.js";

const addValue = (doc, label, value, x, y, width = 225) => {
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#69455a").text(label.toUpperCase(), x, y, { width });
  doc.font("Helvetica").fontSize(11).fillColor("#20151b").text(String(value ?? "-"), x, y + 14, { width });
};

export const generateReadingResultPDF = ({ assessmentNumber, student, result, completedAt }) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 44, bufferPages: true });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const contentWidth = pageWidth - 88;
    doc.rect(0, 0, pageWidth, 132).fill("#633fb5");
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(25).text("Let's Read India", 44, 38);
    doc.fontSize(15).text("Reading Age Assessment Result", 44, 72);
    doc.font("Helvetica").fontSize(9).text(`Assessment ${assessmentNumber}`, 44, 101);

    let y = 158;
    addValue(doc, "Student", student.name, 44, y);
    addValue(doc, "Age", `${student.age_years} years`, 305, y);
    y += 54;
    addValue(doc, "Class / Grade", student.class_name, 44, y);
    addValue(doc, "School", student.school_name, 305, y);
    y += 54;
    addValue(doc, "Location", `${student.city}, ${student.country}`, 44, y);
    addValue(doc, "Completed", new Date(completedAt || Date.now()).toLocaleString("en-IN"), 305, y);

    y += 68;
    doc.roundedRect(44, y, contentWidth, 126, 14).fill("#f3effc");
    doc.fillColor("#633fb5").font("Helvetica-Bold").fontSize(12).text("READING AGE", 62, y + 20);
    doc.fillColor("#20151b").fontSize(27).text(result.reading_age_code, 62, y + 40);
    doc.font("Helvetica").fontSize(10).fillColor("#69455a").text(formatReadingAge(result.reading_age_code), 62, y + 77);
    doc.fillColor("#633fb5").font("Helvetica-Bold").fontSize(12).text("ASSESSMENT", 305, y + 20);
    doc.fillColor("#20151b").fontSize(18).text(result.classification, 305, y + 43, { width: 225 });
    doc.font("Helvetica").fontSize(9).fillColor("#69455a").text(result.intervention, 305, y + 79, { width: 225 });

    y += 150;
    doc.fillColor("#20151b").font("Helvetica-Bold").fontSize(14).text("Summary", 44, y);
    y += 28;
    addValue(doc, "Correct answers", result.correct_count, 44, y, 120);
    addValue(doc, "Incorrect answers", result.incorrect_count, 176, y, 120);
    addValue(doc, "Last correct answer", result.last_correct_item || "None", 308, y, 220);
    y += 62;
    const gap = result.reading_gap_months;
    addValue(doc, "Reading gap", gap === null ? "Not available" : gap > 0 ? `${gap} month(s) below chronological age` : gap < 0 ? `${Math.abs(gap)} month(s) above chronological age` : "Age appropriate", 44, y, contentWidth);

    doc.addPage();
    doc.fillColor("#20151b").font("Helvetica-Bold").fontSize(17).text("Assessment Response History", 44, 44);
    y = 82;
    const drawHeader = () => {
      doc.rect(44, y, contentWidth, 24).fill("#633fb5");
      doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(8);
      doc.text("#", 52, y + 8, { width: 24 }); doc.text("ITEM", 82, y + 8, { width: 260 });
      doc.text("RA KEY", 354, y + 8, { width: 65 }); doc.text("RESULT", 430, y + 8, { width: 95 });
      y += 24;
    };
    drawHeader();
    (result.responses || []).forEach((response, index) => {
      const height = Math.max(24, doc.heightOfString(response.item_text, { width: 260 }) + 12);
      if (y + height > 748) { doc.addPage(); y = 44; drawHeader(); }
      if (index % 2 === 0) doc.rect(44, y, contentWidth, height).fill("#faf8ff");
      doc.fillColor("#20151b").font("Helvetica").fontSize(8);
      doc.text(String(index + 1), 52, y + 8, { width: 24 }); doc.text(response.item_text, 82, y + 8, { width: 260 });
      doc.text(response.ra_key, 354, y + 8, { width: 65 });
      doc.fillColor(response.is_correct ? "#13795b" : "#c7363f").font("Helvetica-Bold")
        .text(response.is_correct ? "Correct" : "Incorrect", 430, y + 8, { width: 95 });
      y += height;
    });

    const pages = doc.bufferedPageRange();
    for (let page = pages.start; page < pages.start + pages.count; page += 1) {
      doc.switchToPage(page);
      doc.fillColor("#8c7582").font("Helvetica").fontSize(8)
        .text(`Generated by Let's Read India | Page ${page + 1} of ${pages.count}`, 44, 780, { width: contentWidth, align: "center", lineBreak: false });
    }
    doc.end();
  });
